namespace KISS.FluentSqlBuilder.Decorators.LimitDecorators;

/// <summary>
///     Provides the SQL query construction logic for the <see cref="LimitDecorator"/>.
///     This class appends LIMIT (or TOP) clauses to restrict the number of rows returned
///     by the query, building on the SQL generated by the inner decorator.
/// </summary>
public sealed partial record LimitDecorator
{
    /// <inheritdoc />
    public override string Sql
    {
        get
        {
            SqlBuilder.Clear();
            Append(Inner.Sql);

            // Append the LIMIT clause(s) from the configured statements.
            new EnumeratorProcessor<string>(SqlStatements[SqlStatement.Limit])
                .AccessFirst(fs =>
                {
                    Append("LIMIT");
                    AppendLine($"{fs}");
                    AppendLine();
                })
                .Execute();

            // Return the complete SQL query as a string.
            return SqlBuilder.ToString();
        }
    }
}
