global using System;
global using System.Linq;
global using System.IO;
global using System.Diagnostics.CodeAnalysis;
global using System.Collections.Generic;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using KISS.FluentEmail.Models;
