# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Integration and Delivery

on:
    push:
        branches: [ "main", "develop" ]
        # paths:
        #   - "src/**"
    pull_request:
        branches: [ "main", "develop" ]

# env:
#     configuration: release

jobs:
    build:
        
        runs-on: ubuntu-latest
        env:
            coverageReportPath: ${{ github.workspace }}/coverage-reports/
            mergedCoverageReportFileName: merged-coverage.xml
        
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 8.0.x
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Build
                run: dotnet build --no-restore
            -   name: Run unit tests
                run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ${{ env.coverageReportPath }} -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura
            -   name: Install dotnet-coverage
                run: dotnet tool install --global dotnet-coverage
            -   name: Merge coverage reports
                run: dotnet-coverage merge ${{ env.coverageReportPath }}**/*.xml -f cobertura -o ${{ env.coverageReportPath }}${{ env.mergedCoverageReportFileName }}
            -   name: Codecov
                uses: codecov/codecov-action@v4
                with:
                    directory: ${{ env.coverageReportPath }}
                    files: ${{ env.mergedCoverageReportFileName }}
                    token: ${{ secrets.CODECOV_TOKEN }}