namespace KISS.FluentSqlBuilder.Decorators.OffsetDecorators;

/// <summary>
///     Provides the SQL query construction logic for the <see cref="OffsetDecorator"/>.
///     This class appends OFFSET clauses to SQL queries, enabling result set pagination
///     by skipping a specified number of rows, and builds on the SQL generated by the inner decorator.
/// </summary>
public sealed partial record OffsetDecorator
{
    /// <inheritdoc />
    public override string Sql
    {
        get
        {
            SqlBuilder.Clear();
            Append(Inner.Sql);

            // Append the OFFSET clause(s) from the configured statements.
            new EnumeratorProcessor<string>(SqlStatements[SqlStatement.Offset])
                .AccessFirst(fs =>
                {
                    Append("OFFSET");
                    AppendLine($"{fs}");
                    AppendLine();
                })
                .Execute();

            // Return the complete SQL query as a string.
            return SqlBuilder.ToString();
        }
    }
}
